version: "2.2"

networks:
    assignment-project-network:

volumes:
    mysqldata:
        driver: "local"

services:
    assignment-project:
        container_name: assignment-project
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - assignment-mysql
        volumes:
            - .:/var/www/html/public
            - /var/www/html/public/vendor
            - /var/www/html/public/node_modules
        ports:
            - 8085:80
        environment:
            - WEB_DOCUMENT_ROOT=/var/www/html/public/public
        networks:
            - assignment-project-network
        restart: on-failure

    assignment-mysql:
        container_name: assignment-mysql
        image: mysql:5.7
        volumes:
            # - mysqldata:/var/lib/mysql
            # - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./database/start-sql/:/docker-entrypoint-initdb.d
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: assignment
            MYSQL_USER: assignment
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - assignment-project-network
        restart: on-failure